import DeckTypes from '../components/Bus/DeckTypes'

const seatData = [
    {
        _id: '1',
        seatType: 'Standard',
        userId: '',
        seatNo: 1,
        createdAt: new Date('2024-02-21T08:00:00Z'),
        seatStatus: {
            available: true,
            reserved: true,
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '2',
        seatType: 'Premium',
        userId: '5',
        seatNo: 2,
        createdAt: new Date('2024-02-20T10:00:00Z'),
        seatStatus: {
            available: false,
            reserved: true,
            maleSeat: false,
            femaleSeat: true,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '3',
        seatType: 'Standard',
        seatNo: 3,
        userId: '',
        createdAt: new Date('2024-02-19T09:00:00Z'),
        seatStatus: {
            available: true,
            reserved: false,
            maleSeat: true,
            femaleSeat: true,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '4',
        seatType: 'Economy',
        seatNo: 4,
        userId: '',
        createdAt: new Date('2024-02-18T11:00:00Z'),
        seatStatus: {
            available: true,
            reserved: false,
            maleSeat: false,
            femaleSeat: true,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '5',
        seatType: 'Business',
        seatNo: 5,
        userId: '3',
        createdAt: new Date('2024-02-17T13:00:00Z'),
        seatStatus: {
            available: false,
            reserved: true,
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '6',
        seatType: 'Standard',
        seatNo: 6,
        userId: '',
        createdAt: new Date('2024-02-16T14:00:00Z'),
        seatStatus: {
            available: true,
            reserved: false,
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '7',
        seatType: 'Premium',
        seatNo: 7,
        userId: '',
        createdAt: new Date('2024-02-15T15:00:00Z'),
        seatStatus: {
            available: true,
            reserved: false,
            maleSeat: true,
            femaleSeat: true,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '8',
        seatType: 'Economy',
        seatNo: 8,
        userId: '',
        createdAt: new Date('2024-02-14T16:00:00Z'),
        seatStatus: {
            available: true,
            reserved: false,
            maleSeat: false,
            femaleSeat: true,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '9',
        seatType: 'Business',
        seatNo: 9,
        userId: '7',
        createdAt: new Date('2024-02-13T17:00:00Z'),
        seatStatus: {
            available: false,
            reserved: true,
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '10',
        seatType: 'Standard',
        seatNo: 10,
        userId: '',
        createdAt: new Date('2024-02-12T18:00:00Z'),
        seatStatus: {
            available: true,
            reserved: false,
            maleSeat: false,
            femaleSeat: false,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '11',
        seatType: 'Premium',
        seatNo: 11,
        createdAt: new Date('2024-02-11T19:00:00Z'),
        seatStatus: {
            available: true,
            reserved: false,
            maleSeat: true,
            femaleSeat: true,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '12',
        seatType: 'Economy',
        seatNo: 12,
        userId: '',
        createdAt: new Date('2024-02-10T20:00:00Z'),
        seatStatus: {
            available: true,
            reserved: false,
            maleSeat: false,
            femaleSeat: true,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '13',
        seatType: 'Business',
        seatNo: 13,
        userId: '6',
        createdAt: new Date('2024-02-09T21:00:00Z'),
        seatStatus: {
            available: false,
            reserved: true,
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '14',
        seatType: 'Standard',
        seatNo: 14,
        userId: '',
        createdAt: new Date('2024-02-08T22:00:00Z'),
        seatStatus: {
            available: true,
            reserved: false,
            maleSeat: false,
            femaleSeat: false,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '15',
        seatType: 'Premium',
        seatNo: 15,
        userId: '',
        createdAt: new Date('2024-02-07T23:00:00Z'),
        seatStatus: {
            available: true,
            reserved: false,
            maleSeat: true,
            femaleSeat: true,
        },
        deck: DeckTypes.UPPER_DECK,
    },
]

export default seatData
