import DeckTypes from '../components/Bus/DeckTypes'

const seatData = [
    {
        _id: '1',
        seatType: 'Standard',
        userId: '',
        seatNumber: 1,
        createdAt: new Date('2024-02-21T08:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '2',
        seatType: 'Premium',
        userId: '',
        seatNumber: 2,
        createdAt: new Date('2024-02-20T10:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: true,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '3',
        seatType: 'Standard',
        seatNumber: 3,
        userId: '',
        createdAt: new Date('2024-02-19T09:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: true,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '4',
        seatType: 'Economy',
        seatNumber: 4,
        userId: '',
        createdAt: new Date('2024-02-18T11:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: true,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '5',
        seatType: 'Business',
        seatNumber: 5,
        userId: '',
        createdAt: new Date('2024-02-17T13:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '6',
        seatType: 'Standard',
        seatNumber: 6,
        userId: '',
        createdAt: new Date('2024-02-16T14:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '7',
        seatType: 'Premium',
        seatNumber: 7,
        userId: '',
        createdAt: new Date('2024-02-15T15:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: true,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '8',
        seatType: 'Economy',
        seatNumber: 8,
        userId: '',
        createdAt: new Date('2024-02-14T16:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: true,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '9',
        seatType: 'Business',
        seatNumber: 9,
        userId: '',
        createdAt: new Date('2024-02-13T17:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '10',
        seatType: 'Standard',
        seatNumber: 10,
        userId: '',
        createdAt: new Date('2024-02-12T18:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: false,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '11',
        seatType: 'Premium',
        seatNumber: 11,
        userId: '',
        createdAt: new Date('2024-02-11T19:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: true,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '12',
        seatType: 'Economy',
        seatNumber: 12,
        userId: '',
        createdAt: new Date('2024-02-10T20:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: true,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '13',
        seatType: 'Business',
        seatNumber: 13,
        userId: '',
        createdAt: new Date('2024-02-09T21:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '14',
        seatType: 'Standard',
        seatNumber: 14,
        userId: '',
        createdAt: new Date('2024-02-08T22:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: false,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '15',
        seatType: 'Premium',
        seatNumber: 15,
        userId: '',
        createdAt: new Date('2024-02-07T23:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: true,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '16',
        seatType: 'Economy',
        seatNumber: 16,
        userId: '',
        createdAt: new Date('2024-02-06T08:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '17',
        seatType: 'Business',
        seatNumber: 17,
        userId: '',
        createdAt: new Date('2024-02-05T10:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: true,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '18',
        seatType: 'Standard',
        seatNumber: 18,
        userId: '',
        createdAt: new Date('2024-02-04T12:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: true,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '19',
        seatType: 'Premium',
        seatNumber: 19,
        userId: '',
        createdAt: new Date('2024-02-03T14:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: false,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '20',
        seatType: 'Economy',
        seatNumber: 20,
        userId: '',
        createdAt: new Date('2024-02-02T16:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '21',
        seatType: 'Business',
        seatNumber: 21,
        userId: '',
        createdAt: new Date('2024-02-01T18:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: true,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '22',
        seatType: 'Standard',
        seatNumber: 22,
        userId: '',
        createdAt: new Date('2024-01-31T20:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: true,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '23',
        seatType: 'Premium',
        seatNumber: 23,
        userId: '',
        createdAt: new Date('2024-01-30T22:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: false,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '24',
        seatType: 'Economy',
        seatNumber: 24,
        userId: '',
        createdAt: new Date('2024-01-29T23:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '25',
        seatType: 'Business',
        seatNumber: 25,
        userId: '',
        createdAt: new Date('2024-01-28T01:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: true,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '26',
        seatType: 'Standard',
        seatNumber: 26,
        userId: '',
        createdAt: new Date('2024-01-27T03:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: true,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '27',
        seatType: 'Premium',
        seatNumber: 27,
        userId: '',
        createdAt: new Date('2024-01-26T05:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: false,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '28',
        seatType: 'Economy',
        seatNumber: 28,
        userId: '',
        createdAt: new Date('2024-01-25T07:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '29',
        seatType: 'Business',
        seatNumber: 29,
        userId: '',
        createdAt: new Date('2024-01-24T09:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: true,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '30',
        seatType: 'Standard',
        seatNumber: 30,
        userId: '',
        createdAt: new Date('2024-01-23T11:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: true,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '31',
        seatType: 'Premium',
        seatNumber: 31,
        userId: '',
        createdAt: new Date('2024-01-22T13:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: false,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '32',
        seatType: 'Economy',
        seatNumber: 32,
        userId: '',
        createdAt: new Date('2024-01-21T15:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '33',
        seatType: 'Business',
        seatNumber: 33,
        userId: '',
        createdAt: new Date('2024-01-20T17:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: true,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '34',
        seatType: 'Standard',
        seatNumber: 34,
        userId: '',
        createdAt: new Date('2024-01-19T19:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: true,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '35',
        seatType: 'Premium',
        seatNumber: 35,
        userId: '',
        createdAt: new Date('2024-01-18T21:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: false,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '36',
        seatType: 'Economy',
        seatNumber: 36,
        userId: '',
        createdAt: new Date('2024-01-17T23:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '37',
        seatType: 'Business',
        seatNumber: 37,
        userId: '',
        createdAt: new Date('2024-01-16T01:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: true,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '38',
        seatType: 'Standard',
        seatNumber: 38,
        userId: '',
        createdAt: new Date('2024-01-15T03:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: true,
        },
        deck: DeckTypes.LOWER_DECK,
    },
    {
        _id: '39',
        seatType: 'Premium',
        seatNumber: 39,
        userId: '',
        createdAt: new Date('2024-01-14T05:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: false,
            femaleSeat: false,
        },
        deck: DeckTypes.UPPER_DECK,
    },
    {
        _id: '40',
        seatType: 'Economy',
        seatNumber: 40,
        userId: '',
        createdAt: new Date('2024-01-13T07:00:00Z'),
        available: true,
        seatStatus: {
            maleSeat: true,
            femaleSeat: false,
        },
        deck: DeckTypes.LOWER_DECK,
    },
]

export default seatData
